Repository PlaceOS/models, pull requests merged in 2022-02, with the labels that each got.

#139 fix(settings): return previous order of settings
  shard.yml
  src/placeos-models/settings.cr
  src/placeos-models/utilities/settings_helper.cr
Labels: type: bug

#140 feat(user): add department and preferred_language
  shard.yml
  spec/user_spec.cr
  src/placeos-models/user.cr
Labels: priority: medium, product: placeos, focus: backend

#138 refactor!(error): better namespacing for errors
  spec/api_key_spec.cr
  src/placeos-models/api_key.cr
  src/placeos-models/error.cr
  src/placeos-models/module.cr
  src/placeos-models/settings.cr
Labels: on ice, type: refactor

#142 feat: add openapi-serializable
  shard.yml
  src/placeos-models/base/model.cr
  src/placeos-models/module.cr
  src/placeos-models/user_jwt.cr
Labels: type: enhancement, focus: documentation

#141 refactor: edge api key
  shard.yml
  spec/edge_spec.cr
  spec/generator.cr
  src/placeos-models/edge.cr
Labels: type: maintenance, type: refactor

#143 feat(edge): add edge-control scope
  shard.yml
  src/placeos-models/edge.cr
Labels: type: enhancement

#145 refactor(edge): move key clean-up to `save!`
  shard.yml
  spec/edge_spec.cr
  spec/generator.cr
  src/placeos-models/edge.cr
Labels: type: bug
