Repository PlaceOS/models, pull requests merged in 2022-04, with the labels that each got.

#163 refactor!(metadata): remove string backed `details` object
  spec/metadata_spec.cr
  src/placeos-models/metadata.cr
  src/placeos-models/trigger/conditions.cr
  src/placeos-models/user_jwt.cr
Labels: type: refactor

#164 feat(metadata): implement queries
  shard.yml
  spec/metadata_spec.cr
  src/placeos-models/metadata.cr
Labels: type: enhancement

#167 feat(metadata#query): add ability to filter by name
  spec/metadata_spec.cr
  src/placeos-models/metadata.cr
Labels: type: enhancement

#168 fix(User#find_by_email): digest was not used
  spec/generator.cr
  spec/helper.cr
  spec/module_spec.cr
  src/placeos-models/user.cr
Labels: type: bug

#169 fix(last_modified): ensure `modified_by_id` is serialised
  spec/api_key_spec.cr
  spec/asset_instance_spec.cr
  spec/asset_spec.cr
  spec/authority_spec.cr
  spec/broker_spec.cr
  spec/control_system_spec.cr
  spec/driver_spec.cr
  spec/edge_spec.cr
  spec/generator.cr
  spec/helper.cr
  spec/json_schema_spec.cr
  spec/metadata_spec.cr
  spec/module_spec.cr
  spec/repository_spec.cr
  spec/settings_spec.cr
  spec/trigger_instance_spec.cr
  spec/trigger_spec.cr
  spec/user_spec.cr
  spec/zone_spec.cr
  src/placeos-models/trigger_instance.cr
  src/placeos-models/utilities/last_modified.cr
Labels: type: bug

#170 fix(metadata#query): allow `@` and ` ` in keys and values
  spec/metadata_spec.cr
  src/placeos-models/metadata.cr
Labels: priority: critical, type: bug

#171 feat(user): expose commonly required fields
  shard.yml
  src/placeos-models/user.cr
Labels: squad: core, type: enhancement, product: placeos, priority: critical, focus: backend
