Repository PlaceOS/models, pull requests merged in 2024-08, with the labels that each got.

#269 feat: PPT-1470 Add email domain feature to Authority model
  migration/db/migrations/202408051121000_alter_authority_add_email_domains.sql
  spec/authority_spec.cr
  spec/generator.cr
  src/placeos-models/authority.cr
  src/placeos-models/module.cr
  test
Labels: type: enhancement

#270 feat(playlist/item): add video length
  migration/db/migrations/202408060000000_alter_uploads_more_metadata.sql
  src/placeos-models/playlist/item.cr
Labels: type: enhancement

#271 fix(authority): Add migration script to set defaults
  migration/db/migrations/202408060100000_alter_authority_add_default_email_domains.sql
  src/placeos-models/authority.cr
Labels: type: bug

#272 refactor(booking): change induction to an enum
  migration/db/migrations/202408131534000_alter_bookings_change_induction_to_enum.sql
  src/placeos-models/booking.cr
Labels: type: refactor

#274 feat(user): [PPT-1484] format of work_preferences and work_overrides
  src/placeos-models/user.cr
Labels: type: enhancement
