Repository PlaceOS/models, pull requests merged in 2024-02, with the labels that each got.

#247 feat(zone): [PPT-1154] add auto_release
  migration/db/migrations/202402071243000_add_auto_release_to_zone.sql
  spec/zone_spec.cr
  src/placeos-models/zone.cr
Labels: type: enhancement

#248 refactor(zone): [PPT-1154] remove unused field
  migration/db/migrations/202402121454000_remove_auto_release_from_zone.sql
  spec/zone_spec.cr
  src/placeos-models/zone.cr
Labels: type: refactor

#250 fix(booking): #clashing? with asset_ids
  src/placeos-models/booking.cr
Labels: type: bug

#251 fix(survey): make Survey::Invitation.list(sent: false) return unsent invites
  spec/generator.cr
  spec/survey_invitation_spec.cr
  spec/survey_question_spec.cr
  spec/survey_spec.cr
  src/placeos-models/survey/invitation.cr
Labels: type: bug

#252 fix(bookings): details specs for desired behaviour [PROJ-636]
  spec/booking_spec.cr
  src/placeos-models/booking.cr
Labels: type: bug

#253 feat: PPT-1224 Add secret_expiry attribute to tenant model
  migration/db/migrations/202402291555000_alter_tenants_add_secret_expiry.sql
  spec/tenant_spec.cr
  src/placeos-models/tenant.cr
Labels: type: enhancement
